### ISSUE TITLE
Why do you write the api with rust?

### ISSUE THREAD

**Issue by Praying** [escwdev/kucoin_rs#7]
I noticed that you have write the kucoin api the node, and why do you rewrite it with rust? Just for fun or any necessity？ And the performance of node is enough for high frequency trading？

**Comment by escwdev** [comment]
I wrote this version so I could better scale some of our trading systems. The Node version's performance was pretty good, and I saw considerable success using it. It was used for some high-frequency trading systems.

Rust just provides a lot more ways to optimize code. Threading in particular is a useful addition. I looked at several typed and compiled languages and settled on Rust for a number of reasons mostly around efficiency and speed.

**Comment by Praying** [comment]
thanks for your explaination, and your good job give me huge inspiration!
