### ISSUE TITLE
Crate name change

### ISSUE THREAD

**Issue by tekjar** [escwdev/kucoin_rs#8]
Crate name 'kucoin' seems to be available on crates.io. Would you like to rename this crate?

Repository name can remain the same to not clash with other language implementations

**Comment by escwdev** [comment]
I'd rather leave it as is. I don't have any knowledge as to whether Kucoin will officially provide any Rust based services in the future, but I'd rather leave the name available for them if they do.

Also, while I'm not currently working on any other open source wrappers, I may in the future and I would like to continue with the `Name_rs` naming convention  - assuming they're available.
